import type { Word } from '@cp949/react-wordcloud';

export const sampleWords: Word[] = [
  { text: 'React', value: 100 },
  { text: 'TypeScript', value: 90 },
  { text: 'JavaScript', value: 85 },
  { text: 'Next.js', value: 80 },
  { text: 'D3.js', value: 75 },
  { text: 'Wordcloud', value: 70 },
  { text: 'Visualization', value: 65 },
  { text: 'Component', value: 60 },
  { text: 'Modern', value: 55 },
  { text: 'Security', value: 50 },
  { text: 'Performance', value: 48 },
  { text: 'Testing', value: 45 },
  { text: 'ESLint', value: 42 },
  { text: 'Prettier', value: 40 },
  { text: 'Vitest', value: 38 },
  { text: 'Turborepo', value: 35 },
  { text: 'Monorepo', value: 33 },
  { text: 'pnpm', value: 30 },
  { text: 'Build', value: 28 },
  { text: 'Deploy', value: 25 },
  { text: 'CSS', value: 23 },
  { text: 'HTML', value: 20 },
  { text: 'SVG', value: 18 },
  { text: 'Animation', value: 15 },
  { text: 'Transition', value: 12 },
  { text: 'Interactive', value: 10 },
  { text: 'Responsive', value: 8 },
  { text: 'Tooltip', value: 6 },
  { text: 'Color', value: 4 },
  { text: 'Font', value: 2 },
];
